dist: bionic
language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
install:
  - npm install -g serverless
  - npm install
jobs:
  include:
    - name: master branch
      script: sls deploy
      if: branch = master
    - name: develop branch
      script: sls deploy --TABLE_NAME stat-develop  --stage develop
      if: branch = develop
